config/routes.rb
Rails.application.routes.draw do
  resources :words
    root "words#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/word.rb
class Word < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  def self.ransackable_attributes(auth_object = nil)
    [ "title" ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [ :show, :edit, :update, :destroy ]
  def index
      @words = Word.all

      @q = Word.ransack(params[:q])
      @words = @q.result.order("title ASC")
  end

  def show
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to @word, notice: "Word was sucessefully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @word.update(word_params)
      redirect_to @word, notice: "Word was sucessfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    redirect_to root_path, notice: "Word was sucessfully deleted!"
  end

  private
  def set_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Personal Dictionary" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<%= stylesheet_link_tag("style") %>

<%= form_with model: word do |form| %>

<div class="col-sm-4">
    <div class="col-auto">
      <%= form.text_field :title, placeholder: "Word title",
     class: "form-control" %>
    <% word.errors.full_messages_for(:title).each do |message| %>
    <div><%=message%></div>
    <%end%>
  </div>
  <br>
  <div class="col-auto">
    <%= form.text_area :description, placeholder: "Word description",
     class: "form-control col-4" %>
    <% word.errors.full_messages_for(:description).each do |message| %>
    <div><%=message%></div>
    <%end%>
  </div>
  <br>
  <div class="col-auto">
    <%= form.submit class: "btn btn-success" %>
  </div>
</div>

<% end %>

<%= link_to "Back", root_path, class: "btn btn-warning mt-2" %>

app/views/words/edit.html.erb
<%= stylesheet_link_tag("style") %>

<h1>Edit Word</h1>

<%= render "form", word: @word %>

app/views/words/index.html.erb
<%= stylesheet_link_tag("style") %>
<h1>Personal Dictionary</h1>

<div class="row">
  <div class="col-auto">
    <%= search_form_for @q do |f| %>

    <%= f.search_field :title_cont,
    placeholder: "Search a word",
    class: "form-control" %>
    
  </div>
  
  <div class="col-auto">
    <%= f.submit class: "btn btn-primary" %>
    
  </div>
  <% end %>
</div>

<%= link_to "Add new word ", new_word_path, class: "btn btn-secondary mt-2" %>

<ul>
  <% @words.each do |word| %>
    <li>
        <%= link_to word.title, word %>
    </li>
  <% end %>
</ul>

app/views/words/new.html.erb
<%= stylesheet_link_tag("style") %>

<h1>New word</h1>

<%= render "form", word: @word %>

app/views/words/show.html.erb
<%= stylesheet_link_tag("style") %>

<div class="">
  <h1><%= @word.title %></h1>
  
  <h4><%= @word.description %></h4>

</div>
  
<ul>
  <li><%= link_to "Edit", edit_word_path(@word), class: "btn btn-info" %></li>
  <li><%= button_to "Delete", word_path(@word),
  method: :delete, data: { "turbo-confirm": "Are you sure?" },
  class: "btn btn-danger mt-2" %></li>
  <li><%= link_to "Back", root_path, class: "btn btn-warning mt-2" %></li>
</ul>